In [1]:
import pandas as pd
import json
import os

In [2]:
json_file = "purchase_data.json"

pymoli_pd = pd.read_json(json_file)

gaming_df = pd.DataFrame(pymoli_pd, columns =['SN','Age','Item ID','Item Name','Price'])
gaming_df.head()

,SN,Age,Item ID,Item Name,Price
0,Aelalis34,38,165,Bone Crushing Silver Skewer,3.37
1,Eolo46,21,119,"Stormbringer, Dark Blade of Ending Misery",2.32
2,Assastnya25,34,174,Primitive Blade,2.46
3,Pheusrical25,21,92,Final Critic,1.36
4,Aela59,23,63,Stormfury Mace,1.27

In [3]:
#Total players
length_players = len(gaming_df['SN'].value_counts())
df_total_players = pd.DataFrame({"Total Players": length_players}, index =[0])
df_total_players

   Total Players
0            573

# Purchasing Total

In [4]:
#Purchasing Analysis

#Number of Unique Items 
df_unique_items = len(gaming_df['Item Name'].value_counts())
df_unique_items
#Average Purchase Price
df_average_price = gaming_df['Price'].mean()
df_average_price
#Total Number of Purchases
df_Total_Purchase = len(gaming_df)
df_Total_Purchase
#Total Revenue
df_total_revenue = gaming_df['Price'].sum()
df_total_revenue
#dataframe
purchasing_Total = pd.DataFrame({"Unique Items":[df_unique_items],"Average Price":[df_average_price],"Total Purchase":[df_Total_Purchase],"Total Revenue":[df_total_revenue]}, index = [0])

#print
purchasing_Total

#improvements.. change to 2 decimal pts .. dollar signs etc..

   Average Price  Total Purchase  Total Revenue  Unique Items
0       2.931192             780        2286.33           179

# Gender DemoGraphics

In [5]:
pymoli_pd.head()
#total players = length_players = len(gaming_df['SN'].value_counts())
#group
players_grouped = pymoli_pd.groupby(["Gender"])
unique_players = players_grouped.nunique()


#total
total_gender = unique_players["SN"].sum()
#Percent and Count of Male Players
tCount = unique_players["SN"].unique()
tPercent = unique_players["SN"]/ length_players



#dataframe & Percentage and Count of Other / Non-Disclosed
tGender = pd.DataFrame({"% of Players": tPercent, "Result":tCount})
tGender

                       % of Players  Result
Gender
Female                     0.174520     100
Male                       0.811518     465
Other / Non-Disclosed      0.013962       8

# Purchasing Analysis (Gender)

In [6]:
#group by gender
gender_group = pymoli_pd.groupby(["Gender"])

#Purchase Count
tPurchase_count = gender_group["SN"].count()

#Average Purchase Price
taveragePrice = gender_group["Price"].mean()
#Total Purchase Value
tPurchase = gender_group ["Price"].sum()
#normalized Totals 
duplicate_data = pymoli_pd.drop_duplicates(subset='SN', keep="first")
grouped_duplicate_data = duplicate_data.groupby(["Gender"])

Norm = (gender_group["Price"].sum() / grouped_duplicate_data["SN"].count())


#dataframe
pAnalysis_df = pd.DataFrame({"Purchase Count":tPurchase_count, "Average Purchase Price": taveragePrice, "Total Purchase Value": tPurchase, "Normalized": Norm })
pAnalysis_df

,Average Purchase Price,Normalized,Purchase Count,Total Purchase Value
Gender,,,,
Female,2.815515,3.829100,136,382.91
Male,2.950521,4.016516,633,1867.68
Other / Non-Disclosed,3.249091,4.467500,11,35.74

In [7]:
#Binning
bins = [0,10,15,20,25,30,35,40,200]
#The below each broken into bins of 4 years (i.e. <10, 10-14, 15-19, etc.)
bin_L = ['Under 10', '10 - 14', '15 - 19', '20 - 24', '25 - 29', '30 - 34', '35 - 39', 'Over 40']

#bin to DF 
bin_df = pymoli_pd.copy()
bin_df["Age Groups"] = pd.cut(bin_df["Age"], bins, labels =bin_L)
bin_C = pd.cut(bin_df["Age"], bins, labels = bin_L)
grouped_bin = bin_df.groupby(["Age Groups"])

bin_count= grouped_bin["SN"].count()
count_total = pymoli_pd["SN"].count()
percent = (bin_count/count_total) *100
percent

A_percent = pd.DataFrame({"Total Count": bin_count,
                           "Percentage of Players": percent})

A_percent["Percentage of Players"] = A_percent["Percentage of Players"].map("{:.2f}%".format)
A_percent.head()

#Purchase Count
#Average Purchase Price
#Total Purchase Value
#Normalized Totals

           Percentage of Players  Total Count
Age Groups
10 - 14                   10.00%           78
15 - 19                   23.59%          184
20 - 24                   39.10%          305
25 - 29                    9.74%           76
30 - 34                    7.44%           58

In [8]:
#Binning
bins = [0,10,15,20,25,30,35,40,200]
#The below each broken into bins of 4 years (i.e. <10, 10-14, 15-19, etc.)
bin_L = ['Under 10', '10 - 14', '15 - 19', '20 - 24', '25 - 29', '30 - 34', '35 - 39', 'Over 40']

#bin to DF 
bin_df = pymoli_pd.copy()
bin_df["Age Groups"] = pd.cut(bin_df["Age"], bins, labels =bin_L)
bin_C = pd.cut(bin_df["Age"], bins, labels = bin_L)
grouped_bin = bin_df.groupby(["Age Groups"])

count_p = grouped_bin["Age"].count()
Average_p = grouped_bin["Price"].mean()
Total_p = grouped_bin["Price"].sum()

#delete dups
duplicate = pymoli_pd.drop_duplicates(subset = 'SN', keep = "first")
duplicate["Age Groups"] = pd.cut(duplicate["Age"], bins, labels = bin_L)
duplicate = duplicate.groupby(["Age Groups"])

bin_normalize = (grouped_bin["Price"].sum()/duplicate["SN"].count())
bin_normalize

#dataframe
age_group_df = pd.DataFrame({"Purchase Count": count_p,
                            "Average Purchase Price": Average_p,
                            "Total Purchase Value": Total_p,
                            "Normalized Totals": bin_normalize})

age_group_df

/Users/zacharyquasney/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Average Purchase Price,Normalized Totals,Purchase Count,Total Purchase Value
Age Groups,,,,
10 - 14,2.873718,4.150926,78,224.15
15 - 19,2.873587,3.803885,184,528.74
20 - 24,2.959377,3.857308,305,902.61
25 - 29,2.892368,4.227308,76,219.82
30 - 34,3.073448,4.051364,58,178.26
35 - 39,2.897500,5.099600,44,127.49
Over 40,2.880000,2.880000,3,8.64
Under 10,3.019375,4.391818,32,96.62

In [9]:
#Top Spenders
#group by SN
SN_group = pymoli_pd.groupby(["SN"])

SN_group_count = SN_group["Item ID"].count()
SN_group_total = SN_group["Price"].sum()
SN_group_Average = (SN_group_total/SN_group_count)

SN_df = pd.DataFrame({"Purchase Count": SN_group_count, "Average Purchase Price": SN_group_Average,"Total Purchase Value":SN_group_total})

SN_df = SN_df.sort_values("Total Purchase Value", ascending = False)
SN_df.head(5)
#Identify the the top 5 spenders in the game by total purchase value, then list (in a table):
#SN
#Purchase Count
#Average Purchase Price
#Total Purchase Value

             Average Purchase Price  Purchase Count  Total Purchase Value
SN
Undirrala66                3.412000               5                 17.06
Saedue76                   3.390000               4                 13.56
Mindimnya67                3.185000               4                 12.74
Haellysu29                 4.243333               3                 12.73
Eoda93                     3.860000               3                 11.58

In [10]:
#Most Popular Items
item_grouped = pymoli_pd.groupby(["Item ID", "Item Name"])
item_grouped_SN = item_grouped["SN"].count()
price_grouped_sum = item_grouped["Price"].sum()
item_grouped_price = (price_grouped_sum/item_grouped_SN)
item_grouped_value = (item_grouped_price * item_grouped_SN)

most_popular_items = pd.DataFrame({"Purchase Count": item_grouped, 
                                   "Item Price": item_grouped_price,
                                   "Total Purchase Value":item_grouped_value})
most_popular_items
#most_popular_items = most_popular_items.sort_values("Purchase Count", ascending = False)
#most_popular_items
#Identify the 5 most popular items by purchase count, then list (in a table):
#Item ID
#Item Name
#Purchase Count
#Item Price
#Total Purchase Value

StopIteration:

StopIteration: